
services:
  # Nginx as the web server
  web:
    image: nginx:alpine
    container_name: frontend-app
    ports:
      - "8081:80"  # Map local port 8081 to Nginx's port 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Custom Nginx configuration
      - ./app:/var/www/html # Mount application files
    depends_on:
      - php # Ensure PHP is running before starting Nginx

  # PHP container running PHP-FPM
  php:
    build: .
    container_name: php-backend
    volumes:
      - ./app:/var/www/html # Mount application files
    expose:
      - "9000" # Expose PHP-FPM on port 9000
    depends_on:
      - db # Ensure MySQL is running before PHP starts

  # MySQL Database
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306" # Expose MySQL on local machine
    volumes:
      - db_data:/var/lib/mysql # Persist database data

volumes:
  db_data:
